desktop:
  hosts:
    localhost:
      ansible_host: localhost
      ansible_connection: local
      ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}'
      ansible_python_interpreter: /usr/bin/python3
