- name: Install desktop software
  hosts: all
  tasks:
  - name: Add the flathub flatpak repository remote to the user installation
    flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: user
  - name: Install Flatpak software
    flatpak:
      name:
        # Flatseal
        - com.github.tchx84.Flatseal
        # Telegram
        - org.telegram.desktop
        # Discord
        - com.discordapp.Discord
      state: present
      method: user
  - name: Add rpm signing key
    become: true
    ansible.builtin.rpm_key:
      key: https://dl.google.com/linux/linux_signing_key.pub
      state: present
  - name: Add Google-Chrome repository
    become: true
    community.general.zypper_repository:
      name: google-chrome
      repo: http://dl.google.com/linux/chrome/rpm/stable/x86_64
      state: present
      auto_import_keys: true
      enabled: true
  - name: Install Google-Chrome and Firefox
    become: true
    community.general.zypper:
      name:
      - google-chrome-stable
      - MozillaFirefox
      state: present

